version: '3.9'

services:
  database:
    image: postgres:16.3
    restart: always
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: desafiovotacaodb
    ports:
      - "5432:5432"
    networks:
      - app_network

  app:
    build:
      context: .
    container_name: maven_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/desafiovotacaodb?useTimezone=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - database
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network: